[package]
name = "tokio-boring"
version = "2.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Ivan Nikulin <ifaaan@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/cloudflare/boring"
homepage = "https://github.com/cloudflare/boring"
documentation = "https://docs.rs/tokio-boring"
description = """
An implementation of SSL streams for Tokio backed by BoringSSL
"""

[dependencies]
boring = { version = "1.1.0", path = "../boring" }
boring-sys = { version = "1.1.0", path = "../boring-sys" }
tokio = "1"

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
