[package]
name = "boring-sys"
version = { workspace = true }
authors = ["Alex Crichton <alex@alexcrichton.com>",
           "Steven Fackler <sfackler@gmail.com>",
           "Ivan Nikulin <ifaaan@gmail.com>"]
license = "MIT"
description = "FFI bindings to BoringSSL"
repository = { workspace = true }
documentation = "https://docs.rs/boring-sys"
links = "boringssl"
readme = "README.md"
categories = ["cryptography", "external-ffi-bindings"]
edition = { workspace = true }
include = [
    "/*.md",
    "/*.toml",
    "/LICENSE-MIT",
    "/cmake/*.cmake",
    "/deps/boringssl/**/*.[chS]",
    "/deps/boringssl/**/*.asm",
    "/deps/boringssl/sources.json",
    "/deps/boringssl/src/crypto/obj/obj_mac.num",
    "/deps/boringssl/src/crypto/obj/objects.txt",
    "/deps/boringssl/**/*.bzl",
    "/deps/boringssl/src/**/*.cc",
    "/deps/boringssl/**/CMakeLists.txt",
    "/deps/boringssl/**/sources.cmake",
    "/deps/boringssl/LICENSE",
    "/deps/boringssl-fips/**/*.[chS]",
    "/deps/boringssl-fips/**/*.asm",
    "/deps/boringssl/sources.json",
    "/deps/boringssl/src/crypto/obj/obj_mac.num",
    "/deps/boringssl/src/crypto/obj/objects.txt",
    "/deps/boringssl-fips/**/*.bzl",
    "/deps/boringssl-fips/src/**/*.cc",
    "/deps/boringssl-fips/**/CMakeLists.txt",
    "/deps/boringssl-fips/**/sources.cmake",
    "/deps/boringssl/LICENSE",
    "/build.rs",
    "/src",
    "/patches",
]

[package.metadata.docs.rs]
features = ["rpk", "pq-experimental"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
# Use a FIPS-validated version of boringSSL in `deps/boringssl-fips`.
fips = []

# Use `deps/boringssl`, but replace the `bcm.o` module with a version provided
# by the user. This allows the `bcm.o` module from the FIPS-validated build of
# `libcrypto.a` to be used with a more recent version of boringSSL.
fips-link-precompiled = []

# Enables Raw public key API (https://datatracker.ietf.org/doc/html/rfc7250)
rpk = []

# Enables experimental post-quantum crypto (https://blog.cloudflare.com/post-quantum-for-all/)
pq-experimental = []

[build-dependencies]
bindgen = { workspace = true }
cmake = { workspace = true }
fs_extra = { workspace = true }
fslock = { workspace = true }
